---
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
#      routes:
#        - id: neo_route
#          uri: https://www.baidu.com
#          predicates:
#          - Path=/spring-cloud
#        - id: cookie_route
#          uri: http://ityouknow.com
#          predicates:
#          - Cookie=ityouknow, kee.e
#        - id: header_route
#          uri: http://ityouknow.com
#          predicates:
#          - Header=X-Request-Id, \d+

  data:
    jpa:
      repositories:
        enabled: false
  datasource:
    username: admin
    #driver-class-name: org.h2.Driver
    #Establishing SSL connection without server's identity verification is not recommened 加上useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/bgcz?zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true&characterEncoding=utf-8
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 4088