---
server:
  port: 8088
spring:
  profiles: user1
  application:
    name: user-service
eureka:
  # 实例的id  默认是myhost:myappname:port  可以配置更改
  #  instance:
  #    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/