---
server:
  port: 8088
spring:
  profiles: user1
  application:
    name: user-service
eureka:
  # 实例的id  默认是myhost:myappname:port  可以配置更改
  #  instance:
  #    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    # 开启健康检测
    healthcheck: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
  instance:
    #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10
#开启hystrix的支持
# 配置对请求的内容的压缩,有了上面spring boot的压缩，此处feign的压缩可以不用
feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: ["text/xml", "application/xml", "application/json"]
      min-request-size: 512
    response:
      enabled: true
  client:
    config:
      # key 为default时表示的是全局配置
      default:
        loggerLevel: basic
      # 为具体的服务提供者的spring.application.name的值，表示单独为这个工程配置
      db-service:
        loggerLevel: full
#配置 db-service的负载策略
#db-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#配置全局的超时时间
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
---
server:
  port: 8089
spring:
  profiles: user2
  application:
    name: user-service
eureka:
  client:
    healthcheck: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #更改Eureka更新频率将打破服务器的自我保护功能，生产环境下不建议自定义这些配置。
  instance:
    #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10