---
#单节点
spring:
  profiles: peer
  application:
    name: eureka-serve
server:
  port: 8761
eureka:
  # false关闭自我保护机制 线上不要改
  server:
    enable-self-preservation: true
    # 清理不可用服务间隔 默认60 * 1000 线上不要改
    eviction-interval-timer-in-ms: 30000
    # 比值
    renewal-percent-threshold: 0.85
    #默认五分钟显示提示信息
    # wait-time-in-ms-when-sync-empty:
    #心跳阈值重新计算的周期 默认是15分钟可以改小一点,比如5分钟=5601000
    #renewal-threshold-update-interval-ms:
  instance:
    hostname: peer
    #续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 30
    #续约更新时间间隔心跳（默认30秒）
    lease-renewal-interval-in-seconds: 10
  client:
    #    这两项配置是表明自己是服务端,不用注册到服务端
    registerWithEureka: false
    fetchRegistry: false
    #    默认服务地址
    serviceUrl:
      defaultZone: http://peer:${server.port}/eureka/

# 多节点
# aplication.name 必须一样
# 服务地址不应该是ip的形式
#
---
spring:
  profiles: peer1
  application:
    name: eureka-serve
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    #向服务端注册使用hostname而不是ip地址的形式
    #true用ip地址注册 同一台服务器多个实例 一定用false
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer3:8763/eureka/,http://peer2:8762/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-serve
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
---
spring:
  profiles: peer3
  application:
    name: eureka-serve
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
